version: '3.9'

services:
  app:
    container_name: app
    image: demo/tuum-test-app
    build: .
    environment:
      DATABASE_HOST: db
      DATABASE_NAME: tuum_test
      DATABASE_USERNAME: test_user
      DATABASE_PASSWORD: ${DATABASE_PASSWORD}
      RABBITMQ_HOST: test-rabbitmq
    depends_on:
      - db
      - rabbitmq
    links:
      - db
    ports:
      - "8080:8080"

  db:
    container_name: postgres
    image: postgres
    environment:
      POSTGRES_USER: test_user
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./db/init_postgres.sql:/docker-entrypoint-initdb.d/init_postgres.sql
    ports:
      - "5432:5432"
    restart: unless-stopped

  rabbitmq:
    container_name: rabbitmq
    hostname: test-rabbitmq
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"

volumes:
  pgdata: